version: "3.9"
services:
  remix:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./prisma/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=temp
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
